using static MCMirror.Internal.CompileTime;
using static MCMirror.Internal.RawMCFunction;

namespace MCMirror.Internal {
    /// <summary>
    /// This class is for use with all autogenerated testing code. There should
    /// be no need to touch this yourself.
    /// </summary>
    [CompilerUsesName]
    public static class Testrunner {
        [CompilerUsesName]
        public static int TestsSucceeded = 0;
        [CompilerUsesName]
        public static int TestsFailed = 0;
        [CompilerUsesName]
        public static int TestsSkipped = 0;

        // Settings
        // (Note: As compiler dev static data is reset every time so yeah,
        //  The ingame settings don't matter and it's these here that do.)
        [CompilerUsesName]
        public static int OnlyPrintFails = 0;
        public static int TestMenuAfterTests = 1;
        public static int TestMenuOnLoad = 0;

        [Load]
        public static void Setup() {
            if (TestMenuOnLoad == 1)
                TestrunnerMenu();
        }

        [MCFunction("testrunner")]
        [CompilerUsesName]
        public static void TestrunnerMenu() {
            // This method is auto-filled by the compiler with the menu.

            // *So* close to being worth to autogenerate in the phase.
            if (OnlyPrintFails == 0) {
                if (TestMenuAfterTests == 0) {
                    if (TestMenuOnLoad == 0) {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§c[OnlyPrintFails: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 1\"}}}},{{\"text\":\"§c[TestMenuAfterTests: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 1\"}}}},{{\"text\":\"§c[TestMenuOnLoad: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 1\"}}}}]");
                    } else {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§c[OnlyPrintFails: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 1\"}}}},{{\"text\":\"§c[TestMenuAfterTests: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 1\"}}}},{{\"text\":\"§a[TestMenuOnLoad: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 0\"}}}}]");
                    }
                } else {
                    if (TestMenuOnLoad == 0) {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§c[OnlyPrintFails: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 1\"}}}},{{\"text\":\"§a[TestMenuAfterTests: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 0\"}}}},{{\"text\":\"§c[TestMenuOnLoad: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 1\"}}}}]");
                    } else {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§c[OnlyPrintFails: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 1\"}}}},{{\"text\":\"§a[TestMenuAfterTests: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 0\"}}}},{{\"text\":\"§a[TestMenuOnLoad: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 0\"}}}}]");
                    }
                }
            } else {
                if (TestMenuAfterTests == 0) {
                    if (TestMenuOnLoad == 0) {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§a[OnlyPrintFails: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 0\"}}}},{{\"text\":\"§c[TestMenuAfterTests: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 1\"}}}},{{\"text\":\"§c[TestMenuOnLoad: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 1\"}}}}]");
                    } else {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§a[OnlyPrintFails: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 0\"}}}},{{\"text\":\"§c[TestMenuAfterTests: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 1\"}}}},{{\"text\":\"§a[TestMenuOnLoad: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 0\"}}}}]");
                    }
                } else {
                    if (TestMenuOnLoad == 0) {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§a[OnlyPrintFails: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 0\"}}}},{{\"text\":\"§a[TestMenuAfterTests: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 0\"}}}},{{\"text\":\"§c[TestMenuOnLoad: §4OFF§c] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 1\"}}}}]");
                    } else {
                        Run($"tellraw @a [\"§7Config: \",{{\"text\":\"§a[OnlyPrintFails: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fOnlyPrintFails\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(OnlyPrintFails)} _ 0\"}}}},{{\"text\":\"§a[TestMenuAfterTests: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuAfterTests\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuAfterTests)} _ 0\"}}}},{{\"text\":\"§a[TestMenuOnLoad: §2ON§a] \",\"hoverEvent\":{{\"action\":\"show_text\",\"contents\":[\"§7Click to toggle §fTestMenuOnLoad\"]}},\"clickEvent\":{{\"action\":\"run_command\",\"value\":\"/scoreboard players set {VarName(TestMenuOnLoad)} _ 0\"}}}}]");
                    }
                }
            }
        }

        [CompilerUsesName]
        public static void PreprocessTestrunner() {
            TestsSucceeded = 0;
            TestsFailed = 0;
            TestsSkipped = 0;
            Run("tellraw @a [\"\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\"]");
        }

        [CompilerUsesName]
        public static void PostprocessTestrunner() {
            if (TestsSkipped == 0) {
                Run($"tellraw @a [\"§fTesting complete: \",{{\"score\":{{\"name\":\"{VarName(TestsSucceeded)}\",\"objective\":\"_\"}},\"bold\":true,\"color\":\"dark_green\"}},\"§a successes; \",{{\"score\":{{\"name\":\"{VarName(TestsFailed)}\",\"objective\":\"_\"}},\"bold\":true,\"color\":\"dark_red\"}},\"§c failures.\"]");
            } else {
                Run($"tellraw @a [\"§fTesting complete: \",{{\"score\":{{\"name\":\"{VarName(TestsSucceeded)}\",\"objective\":\"_\"}},\"bold\":true,\"color\":\"dark_green\"}},\"§a successes; \",{{\"score\":{{\"name\":\"{VarName(TestsFailed)}\",\"objective\":\"_\"}},\"bold\":true,\"color\":\"dark_red\"}},\"§c failures; \",{{\"score\":{{\"name\":\"{VarName(TestsSkipped)}\",\"objective\":\"_\"}},\"bold\":true,\"color\":\"dark_red\"}},\"§c SKIPPED.\"]");
            }
            if (TestMenuAfterTests == 1) {
                Run("tellraw @a [\"\"]");
                TestrunnerMenu();
            }
        }
    }
}
